### ISSUE TITLE
Invalid magic number for header: 6f69 != a5e0

### ISSUE THREAD

**Issue by alex-berliner** [RobbieFernandez/join4together#1]
Hi, I wanted to study your project as an example of GBA development but I seem to have a problem with compilation. 

The root appears to be that on my machine, the asefile library is not able to open your assets.

Sample program:
```
use asefile::AsepriteFile;
use std::path::Path;
fn main() {
    let path = Path::new("/home/alexb/Code/join4together/assets/sprites/quit_text.aseprite");
    let ase = AsepriteFile::read_file(&path).unwrap();
}
```
result:
```
alexb@alexb-XPS-13-9370:~/Code/asetest$ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/asetest`
thread 'main' panicked at src/main.rs:5:46:
called `Result::unwrap()` on an `Err` value: InvalidInput("Invalid magic number for header: 6f69 != a5e0")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is this happening to you? I'm not sure why it would differ on our machines if we are both using the same asefile library. I would appreciate if you checked this out because your project seems like a great starting point for making a GBA game.

System info:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
```

**Comment by RobbieFernandez** [comment]
Hi there! Thanks so much for your interest in my project. 

I've just run a build on my laptop and am not getting that error.
Can you confirm that:
- You are using version 0.3.6 of the asefile library 
- The sha256 of `quit_text.aseprite` is `eb48e471f6cad8f66d267e84ffa871017f3783d4a206ef8af981d91e7141da72`

I'm building it with cargo make, with the command `cargo make -p release rom`. I don't think that will make a difference but maybe worth a try.


Also, for learning GBA games here are some resources that really helped me:
- [The tonc tutorials](https://www.coranac.com/tonc/text/toc.htm), especially the explanations for the sprite data layout were really helpful.
- [GBATEK](https://problemkaputt.de/gbatek.htm#gbasystemcontrol) for data about the hardware 
- [Deku mixer example](https://deku.gbadev.org/program/sound1.html) is a great walkthrough of creating a sound mixer on the GBA. The one I wrote for this game is modelled/copied from this tutorial

And please let me know if you have questions about the code. This is my first big rust project, so I'm sure there's some weird stuff in there haha

**Comment by RobbieFernandez** [comment]
Just confirming your sample code also does not produce any errors on my machine :thinking: 

I'm on opensuse tumbleweed so could be a difference in system libs or something?

**Comment by alex-berliner** [comment]
Hi Robbie, thanks so much for getting back!

I managed to figure it out. Apparently these files were being stored with git-lfs! Very interesting that my original checkout failed since the command even says that `git clone` is supposed to handle this correctly.
```
alexb@alexb-XPS-13-9370:~/Code/join4together$ cat assets/sprites/quit_text.aseprite 
version https://git-lfs.github.com/spec/v1
oid sha256:eb48e471f6cad8f66d267e84ffa871017f3783d4a206ef8af981d91e7141da72
size 355
```
```
alexb@alexb-XPS-13-9370:~/Code/ase2$ git lfs clone https://github.com/RobbieFernandez/join4together/
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
```

Very strange, I've never encountered this before. Whatever the case, after using `git lfs clone` the files were downloaded correctly and I was able to compile. Maybe I'll have to update my git package.

Thanks again for your help and for linking these resources! I was aware of GBATEK but the other two look very interesting.

Cheers,
Alex

**Comment by alex-berliner** [comment]
Last note, `git clone` can actually perform the download correctly now that git-lfs is installed on my machine (I installed it just now between testing clones).

**Comment by RobbieFernandez** [comment]
Hi Alex,

Glad you got it sorted! I haven't touched this repo in a little bit so I forgot I set it to use LFS. 
I'll update the repo with instructions for building it and include that.

Best of luck!
